books/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^search/$', views.search),
]

selfprofile/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from selfprofile import settings
from . import views
# from books import views

urlpatterns = [
    url(r'^dm/$', views.display_meta),
    url(r'^cuv/$', views.current_url_view),
    url(r'^ua/$', views.ua_display),
    url(r'^admin/', admin.site.urls),
    url(r'^hello/$', views.hello),
    url(r'^time/$', views.current_datetime),
    url(r'^time/plus/(\d{1,2})/$', views.hours_ahead),
    url(r'^contact/$', views.contact),
    url(r'^books/', include('books.urls')),
]

# enable urls with special condition
# if settings.DEBUG:
#     urlpatterns += [url(r'^debuginfo/$', views.contact),]

books/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(blank=True)

    def __str__(self):
        return u'%s %s' % (self.first_name, self.last_name)

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.title

selfprofile/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

books/views.py
from django.http import HttpResponse
from django.shortcuts import render
from books.models import Book


# Create your views here.
def search(request):
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append('Enter a search term.')
        elif len(q) > 20:
            errors.append('Please enter at most 20 characters.')
        else:
            books = Book.objects.filter(title__icontains=q)
            return render(request, 'search_results.html', {'books': books, 'query': q})
    return render(request, 'search_form.html', {'errors': errors})

selfprofile/views.py
from django.shortcuts import render
# from django.template.loader import get_template
from django.http import HttpResponse
import datetime
from selfprofile.forms import ContactForm
from django.http import HttpResponseRedirect
from django.core.mail import send_mail

from django.http.response import Http404


def hello(request):
    return HttpResponse("Hello World!")


def current_url_view(request):
    return HttpResponse("Welcome to the page at %s" % request.path)


def ua_display(request):
    try:
        ua = request.META['HTTP_USER_AGENT']
    except KeyError:
        ua = 'unknown'
    return HttpResponse('Your browser is %s' % ua)


def display_meta(request):
    values = request.META.items()
    values = sorted(values, key=lambda values: values[0], reverse=True)
    html = []
    for k, v in values:
        html.append('<tr><td>%s</td><td>%s</td></tr>' % (k, v))
    return HttpResponse('<table>%s</table>' % '\n'.join(html))


def current_datetime(request):
    now = datetime.datetime.now()
    # t = get_template('current_datetime.html')
    # html = t.render({'current_date': now})
    # return HttpResponse(html)
    return render(request, 'current_datetime.html', {'current_date': now})


def hours_ahead(request, offset):
    try:
        offset = int(offset)
    except ValueError:
        raise Http404()
    dt = datetime.datetime.now() + datetime.timedelta(hours=offset)
    html = "<html><body>In %s hour(s), it will be %s." \
           "</body></html>" % (offset, dt)
    return HttpResponse(html)


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(
            initial={'subject': 'I love your site!'}
        )
    return render(request, 'contact_form.html', {'form': form})

templates/contact_form.html
<html>
<head>
<style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 10px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }
</style>
    <title>Contact Us</title>
</head>
<body>
<h1>Contact Us</h1>
{% if form.errors %}
    <p style="color: red;">
        Please correct the error{{ form.errors|pluralize }} below.
    </p>
{% endif %}
<form action="" method="post">
    <div class="field">
        {{ form.subject.errors }}
        <label for="id_subject">Subject:</label>
        {{ form.subject }}
    </div>
    <div class="field">
        {{ form.email.errors }}
        <label for="id_email">Your e-mail address:</label>
        {{ form.email }}
    </div>
    <div class="field {% if form.message.errors %}errors{% endif %}">
        {% if form.message.errors %}
            <ul>
            {%  for error in form.message.errors %}
                <li><strong>{{ error }}</strong></li>
            {% endfor %}
            </ul>
        {% endif %}
        <label for="id_message">Message:</label>
        {{ form.message }}
    </div>
    {% csrf_token %}
    <input type="submit" value="Submit">
</form>
</body>
</html>

templates/current_datetime.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>current datetime</title>
</head>
<body>
It is now {{ current_date }}
</body>
</html>

templates/search_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
</head>
<body>
{% if errors %}
    <ul>
    {% for error in errors %}
        <li>{{ error }}</li>
    {% endfor %}
    </ul>
{% endif %}
    <form action="" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

templates/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Search</title>
</head>
<body>
<p>You searched for: <strong>{{ query }}</strong></p>
{% if books %}
    <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
            <li>{{ book.title }}</li>
        {% endfor %}

    </ul>
{% else %}
    <p>No books matched your search criteria.</p>
{% endif %}
</body>
</html>